# Generated by Django 5.2.1 on 2025-06-06 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
            preserve_default=False,
        ),
    ]
