# Generated by Django 5.2.1 on 2025-06-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_note_pub_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="important",
        ),
    ]
